### ISSUE TITLE
Return flights?

### ISSUE THREAD

**Issue by ersan** [pyro2927/SouthwestCheckin#10]
When I run this script on a round-trip reservation it only seems to be able to check in to the first outgoing flight, is there something I'm missing?

**Comment by pyro2927** [comment]
Hey @ersan! It should work on return flights, however it doesn't do return flights automatically (though that seems like a good enhancement).  Right now you'd just need to run the script _again_ after your initial flight takes off.  This isn't always easy though, especially if you're traveling to a place with no internet.

As of this exact moment the script isn't working per #11.  I'm working on a new branch to resolve these issues.

**Comment by pyro2927** [comment]
@ersan this should be fully working in #13.  Any chance you have a round-trip flight to test with in the coming months?

**Comment by ersan** [comment]
@pyro2927 oh nice, yeah I'll give it a shot I have one coming up in 3 weeks
