### ISSUE TITLE
Not Working Anymore

### ISSUE THREAD

**Issue by rtmill22** [pyro2927/SouthwestCheckin#11]
It seems as though the script is broken, it errors now when trying to pull in reservation info.

**Comment by pyro2927** [comment]
Hey @rtmill22! I noticed this myself when traveling for the holidays this year.  It looks like SW changed a few API calls recently.  I'm working on a branch to fix this: <https://github.com/pyro2927/SouthwestCheckin/tree/thanks_southwest>

**Comment by pyro2927** [comment]
@rtmill22, this should be fully resolved in #13.  Any chance you have a flight coming up to try it with? I have a flight tomorrow and it worked for me 😄

**Comment by rtmill22** [comment]
I have two coming up next week, I will try it and get back to you!

**Comment by msimon3** [comment]
It worked for me!

**Comment by rtmill22** [comment]
Worked great! Thanks!!
