### ISSUE TITLE
No Tests :(

### ISSUE THREAD

**Issue by pyro2927** [pyro2927/SouthwestCheckin#12]
This project has almost zero tests 😢.  I would love it if it had some, but I'm still relatively new to python testing and have no idea the best way to do it.

I can happily supply Southwest API end-point data (grabbed using [Charles](https://www.charlesproxy.com/)) if needed.

**Comment by justinmayer** [comment]
I'm totally swamped at the moment, but I highly recommend [PyTest](https://docs.pytest.org/).

@nicoddemus, et al, have done a great job with the project and its documentation.

**Comment by pyro2927** [comment]
Basic tests have been added, can easily extend for more.
