### ISSUE TITLE
waiting too long

### ISSUE THREAD

**Issue by devksingh4** [pyro2927/SouthwestCheckin#14]
Hello, 
My trip has 2 legs, and it looks like it is checking in for the first leg and not the second leg.

**Comment by pyro2927** [comment]
@andromedastudios1, has the time for the first leg passed already?  It's meant to check you in for both, but only within 24 hours of each departure.

**Comment by andromedastudios1** [comment]
No the time for the first leg had not already passed. I checked in
yesterday by just changing the sleep time to 10 and starting it 12 before.
May this be an issue where southwest changed the way they handle api
requests?


--
Best,
Dev Singh

**Comment by pyro2927** [comment]
Closing as this issue has been resolved with the latest updates.
