### ISSUE TITLE
Should we supply our own API keys?

### ISSUE THREAD

**Issue by zxlin** [pyro2927/SouthwestCheckin#15]
I see there are hard coded `API_KEY` and `USER_EXPERIENCE_KEY` in the checkin script. 

Should we be using these hard coded keys or should individuals obtain their own keys to avoid SWA rejecting these hardcoded API keys? If the latter is true, can we provide a brief description on how to obtain these keys from SWA?

Thanks for the work on this repo!

**Comment by pyro2927** [comment]
@zxlin, nah, no need to supply your own keys.  These were pulled from the [Southwest iOS app](https://itunes.apple.com/us/app/southwest-airlines/id344542975?mt=8) by sniffing app traffic with [Charles](https://www.charlesproxy.com/).
