### ISSUE TITLE
Error: geopy.exc.GeocoderQuotaExceeded

### ISSUE THREAD

**Issue by zxlin** [pyro2927/SouthwestCheckin#16]
I got this error with the `geopy` lib, it seems like Google is unhappy? I'm not particularly familiar with this lib, but maybe we need to get a Google API key. 

```
Traceback (most recent call last):
  File "checkin.py", line 124, in <module>
    auto_checkin(reservation_number, first_name, last_name)
  File "checkin.py", line 108, in auto_checkin
    point = g.geocode(airport).point
  File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/googlev3.py", line 338, in _parse_json
    self._check_status(page.get('status'))
  File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/googlev3.py", line 363, in _check_status
    'The given key has gone over the requests limit in the 24'
geopy.exc.GeocoderQuotaExceeded: The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.
```

**Comment by pyro2927** [comment]
@zxlin do you get that consistently?  Google limits by IP a limit of [2500 requests per day](https://developers.google.com/maps/documentation/geocoding/usage-limits), so unless you're making an unreasonable number of flights that shouldn't be a problem.

**Comment by zxlin** [comment]
Yes, I am still getting it right now. This is a residential IP address, no one else using it but me and I'm not making any requests to Google APIs from this IP.  I've tried it on a VPS on Digital Ocean as well and I'm getting the same result.

**Comment by pyro2927** [comment]
@zxlin you can add one yourself to line [97](https://github.com/pyro2927/SouthwestCheckin/blob/master/checkin.py#L97), by changing it to:

```python
g = geocoders.GoogleV3(api_key="YOUR_KEY")
```

I won't be baking one into the code.
