### ISSUE TITLE
first name has two character

### ISSUE THREAD

**Issue by gettinghub** [pyro2927/SouthwestCheckin#17]
Hi pyro2927,

My first name has two words in it. Should I put a space in it like the usage below?

python ./checkin.py CONFIRMATION_NUMBER FIRST_NAME_1 FIRST_NAME_2 LAST_NAME

Thanks!

**Comment by pyro2927** [comment]
Hey @gettinghub!  I think you can do it like this:

```sh
python ./checkin.py CONF_NUM "FIRSTNAME1 FIRSTNAME2" LASTNAME
```

The quotes allow them to be recognized as a single argument.

**Comment by gettinghub** [comment]
Thank you I will give that a try.
