### ISSUE TITLE
Companion Reservations are not able to be pulled

### ISSUE THREAD

**Issue by h4xdaplanet** [pyro2927/SouthwestCheckin#18]
Getting the following error with a companion reservation:

```
Traceback (most recent call last):
  File "checkin.py", line 125, in <module>
    auto_checkin(reservation_number, first_name, last_name)
  File "checkin.py", line 94, in auto_checkin
    body = lookup_existing_reservation(reservation_number, first_name, last_name)
  File "checkin.py", line 62, in lookup_existing_reservation
    return data['viewReservationViewPage']
KeyError: 'viewReservationViewPage'
```
The parent reservation is working

**Comment by pyro2927** [comment]
I need a better way to track down issues with errors...  Asking people for reservation numbers and full names feels weird.

Did your Companion have the same Reservation Number?  I'm actually a Companion on my wife's account, but I always get a different reservation number so they check-in separately.

**Comment by h4xdaplanet** [comment]
The companion reservation was a separate reservation number, yeah. So was trying to check in separately. I was running this for a friend who had a companion reservation as well in the same timeframe and the same error occurred.

I'm happy to provide names/reservations or provide some debug output - we could do a screenshare or something if that helps? I have companion reservations coming up in the future so have some we could test.

**Comment by kjanoudi** [comment]
My companion reservations work fine, i do believe this can be closed.

**Comment by pctechjon** [comment]
Same. My companion always has a separate confirmation number. I just run two concurrent scripts, one for each confirmation number. Only failed me once when my router went down.
