### ISSUE TITLE
GeocoderQuotaExceeded: The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.

### ISSUE THREAD

**Issue by Raikia** [pyro2927/SouthwestCheckin#19]
Google's geocode api policy has changed now where they severely throttle non-api requests and all APIs now require billing 👎 

Constantly get "GeocoderQuotaExceeded: The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time." now

**Comment by pyro2927** [comment]
@Raikia know of any other geo-coding services?

**Comment by zxlin** [comment]
## Option 1 

There's a project that has data about airports' metadata https://github.com/ryanburnette/airports-api

He's hosted a S3 bucket, example https://airports-api.s3-us-west-2.amazonaws.com/iata/sfo.json or the raw data is available here: https://github.com/ryanburnette/airports-api/blob/master/airport-data/airports.csv (large file)

Example response:
```JSON
{
  "airport_name": "San Francisco Intl",
  "city": "San Francisco",
  "country": "United States",
  "iata": "SFO",
  "icao": "KSFO",
  "latitude": 37.618972,
  "longitude": -122.374889,
  "elevation": 13,
  "utc_offset": -8,
  "_class": "A",
  "timezone": "America/Los_Angeles"
}
```

The author says the data is sourced from Google's API but may be incomplete. Worth a quick poke around 🤔 

## Option 2 

There's a more popular repo that also allows you to query metadata about airports https://github.com/jpatokal/openflights

You can try a sample search from https://openflights.org/html/apsearch, the response looks like: 

```JSON
{
  "status": 1,
  "offset": 0,
  "max": "1",
  "airports": [
    {
      "name": "San Francisco International Airport",
      "city": "San Francisco",
      "country": "United States",
      "iata": "SFO",
      "icao": "KSFO",
      "x": "-122.375",
      "y": "37.61899948120117",
      "elevation": "13",
      "apid": "3469",
      "timezone": "-8",
      "dst": "A",
      "tz_id": "America/Los_Angeles",
      "type": "airport",
      "source": "OurAirports",
      "ap_uid": null,
      "ap_name": "San Francisco Internationa. (SFO), United States"
    }
  ]
}
```

This one seems a lot more promising and has a decent following on Github, the API allows really flexible queries.

**Comment by java007md** [comment]
Using the Google API key is probably the easiest approach.

Another alternative geocoder to consider is GeoNames.org: http://www.geonames.org/export/web-services.html#timezone

**Comment by Raikia** [comment]
I created a pull request #20 which uses the "Option 2".  Tested in both Python 2 and Python 3 so it is still compatible between the two.

**Comment by Raikia** [comment]
Resolved
