### ISSUE TITLE
Send notifications

### ISSUE THREAD

**Issue by pyro2927** [pyro2927/SouthwestCheckin#2]
Southwest has an (undocumented) API for [sending boarding passes to mobile/email](https://github.com/byalextran/luvwrapper/blob/master/lib/luvwrapper.rb#L107).  Either utilize that, or tie in to Twilio in order to notify people when they've checked in (would require API key from Twilio).

**Comment by janina213** [comment]
Hi, I've sent over a pull request (#22) that adds this functionality.  Was able to do some basic testing on my end and it seems to work fine. Let me know if you see any issues that I can fix up.

**Comment by bradzab0623** [comment]
It doesn't work when there is more than 1 person on the reservation. So the script still checks you in, but exits and doesn't check you in for the return flight
[error.txt](https://github.com/pyro2927/SouthwestCheckin/files/2703720/error.txt)

**Comment by pyro2927** [comment]
Closed thanks to #22!
