### ISSUE TITLE
Doesn't work for return flights within 24 hours of outbound flight

### ISSUE THREAD

**Issue by jaredhughes2** [pyro2927/SouthwestCheckin#21]
When it attempts to check in for a return flight that is less than 24 hours after the outbound flight, it just checks in to the outbound flight again and not the return flight.

**Comment by pyro2927** [comment]
Hey @jaredhughes2, any chance you'd be able to test this branch?

https://github.com/pyro2927/SouthwestCheckin/tree/threading

**Comment by shiyuechengineer** [comment]
Hi @pyro2927, getting an error `AttributeError: 'list' object has no attribute 'push'` for the line `threads.push(threading.Thread(target...`. Am I doing something wrong? Thanks for this awesome tool!

**Comment by pyro2927** [comment]
@shiyuechengineer I messed up and didn't properly test the code.  Just pushed up some changes now that work (and have been tested!)

**Comment by pyro2927** [comment]
Closing issue as this has been resolved with #26.
