### ISSUE TITLE
Mobile/email notifications don't work when there is more than 1 person on the reservation. It then exits after the inital checkin and doesn't check in for the return flight

### ISSUE THREAD

**Issue by bradzab0623** [pyro2927/SouthwestCheckin#23]
It doesn't work when there is more than 1 person on the reservation. So the script still checks you in, but exits and doesn't check you in for the return flight
[error.txt](https://github.com/pyro2927/SouthwestCheckin/files/2703720/error.txt)

_Originally posted by @bradzab0623 in https://github.com/pyro2927/SouthwestCheckin/issues/2#issuecomment-449457143_

**Comment by justinmayer** [comment]
I can confirm this problem (cc: @janina213). Invocation and error traceback follow:
```
$ python ./checkin.py SFKPD7 Justin Mayer --email=foobar@gmail.com

Flight information found, departing [redacted] at Jan 07 09:15AM                                              [0/3]
Attempting check-in...
Jane Doe got A43!
Justin Mayer got A44!
Traceback (most recent call last):
  File "./checkin.py", line 155, in <module>
    auto_checkin(reservation_number, first_name, last_name, email, mobile)
  File "./checkin.py", line 143, in auto_checkin
    schedule_checkin(date, reservation_number, first_name, last_name, email, mobile)
  File "./checkin.py", line 114, in schedule_checkin
    send_notification(data, emailaddr=email)
  File "./checkin.py", line 83, in send_notification
    info_needed = checkindata['_links']['boardingPasses']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pyro2927** [comment]
@justinmayer been refactoring a good percentage of the script.  Any way if you can check if the latest version is having these issues for you?  Otherwise I have a flight over Valentine's day weekend I can test with.

**Comment by justinmayer** [comment]
@pyro2927: I would love to but don't have any SW flights planned and probably won't book any for several months. 😥

**Comment by h4xdaplanet** [comment]
I can check on my flight coming up this Fri

**Comment by janina213** [comment]
Hm, I think there may be some more work needed on the send notification side of things.  From @bradzab0623's error info when checking in multiple passengers,
{'_links': None,
 '_v1_infoNeededToViewBoardingPasses': None,
 'flights': [{'boundIndex': 0,
              'departureTime': 'XX:XX',
              'flightNumber': 'XXXX',
              'gate': None,
              'hasWifi': False,
              'passengers': [{'boardingGroup': None,
                              'boardingPosition': None,
                              'checkedIn': True,
                              'confirmationNumber': 'XXXXX',
                              'hasPrecheck': False,
                              **'mobileBoardingPassEligible': False,**
                              'mobileBoardingPassIneligibilityErrorCode': 'MBP_UNAVAILABLE_USE_OTHER_SELF_SERVICE',
                              'name': 'XX XXXX'},
                             {'boardingGroup': 'B',
                              'boardingPosition': '06',
                              'checkedIn': True,
                              'confirmationNumber': 'XXXXX',
                              'hasPrecheck': False,
                              **'mobileBoardingPassEligible': False,**
                              'mobileBoardingPassIneligibilityErrorCode': 'MBP_UNAVAILABLE_USE_OTHER_SELF_SERVICE',
                              'name': 'XXXXXX XXXXXX'}],
              'travelTime': None}]}

From the above, it might not actually be possible to send each passenger their mobile boarding pass, or it may just require a different approach to get to them.  Hard to tell without having an upcoming multi-passenger reservation coming up myself.  Maybe we could figure out what useful data @hx4daplanet can collect that may help with debugging this (if it's a multipassenger trip)?

**Comment by pkarnia** [comment]
Tested today with commit https://github.com/pyro2927/SouthwestCheckin/commit/27122855ee32d6e7043b16851311486cf2b88a39 (traceback below). I have our return flight check-in in ~30 hours so let me know if you want me to gather more verbose prints from this check-in or my return.

```
Attempting check-in...
A got A16!
B got A49!
C got A50!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./checkin.py", line 114, in schedule_checkin
    send_notification(data, emailaddr=email)
  File "./checkin.py", line 83, in send_notification
    info_needed = checkindata['_links']['boardingPasses']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pyro2927** [comment]
It looks like this is an issue we won't be able to code around, as [Southwest doesn't give out mobile boarding passes for reservations with multiple passengers](https://www.southwestaircommunity.com/t5/Check-In/Mobile-Boarding-Pass-not-always-available/m-p/47597/highlight/true#M82).  That said, I'd like to add in a check for `mobileBoardingPassEligible`, and if `False`, presenting the user with a nice error message instead of a stacktrace.

**Comment by msimon3** [comment]
I thought SW updated that issue last year, at least for most types of itineraries.
https://www.southwestaircommunity.com/t5/Southwest-Stories/Travel-Enhancements-amp-International-Booking-Capabilities-Now/ba-p/76709

**Comment by pyro2927** [comment]
@msimon3, it looks like even with the update, you can't get boarding passes for other passengers:
> In this release, users will be able to access their own boarding pass(es). Users will not be able to view or access the other traveler’s passes while logged into their account.

**Comment by msimon3** [comment]
Can it be updated to bypass the notification part? Seems like the checkin aspect still works.

**Comment by pyro2927** [comment]
@msimon3, something like this should work for that:
https://github.com/pyro2927/SouthwestCheckin/tree/no-boarding-passes

Seeing if anyone else has thoughts before merging.

**Comment by janina213** [comment]
Like you mentioned above, may also be worth adding the check for mobileBoardingPassEligible in that same conditional statement.  Adds a little more clarity, and might guard in a weird scenario where links are somehow included but the reservation is ineligible.  Though this is not a blocker.

Overall, I thinke the proposed change set should do the trick.
