### ISSUE TITLE
Script throws an error in the checkin request

### ISSUE THREAD

**Issue by zxlin** [pyro2927/SouthwestCheckin#28]
```
.
.
.
Sorry! We can't check you into this flight. Please see a gate agent.
Sorry! We can't check you into this flight. Please see a gate agent.
Sorry! We can't check you into this flight. Please see a gate agent.
Sorry! We can't check you into this flight. Please see a gate agent.
Attempting check-in...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "checkin.py", line 109, in schedule_checkin
    data = checkin(number, first, last)
  File "checkin.py", line 80, in checkin
    return safe_request(url, info_needed['body'])['checkInConfirmationPage']
  File "checkin.py", line 48, in safe_request
    r = requests.post(url, headers=headers, json=body)
  File "/home/zxl/.local/lib/python2.7/site-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/home/zxl/.local/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

**Comment by pyro2927** [comment]
@zxlin that is a new issue I've not yet seen before.  This will require some digging in.  Can you provide me with any information, as anonymous as you feel comfortable with?

* How many passengers were on the reservation?
* International or domestic flight?
* Multi-stop, or direct?

**Comment by zxlin** [comment]
@pyro2927 

Yup, to answer your questions in order:
- single passenger
- domestic flight
- direct flight

I think this might be a problem with my `requests` package being out of date, my `requests` package version is `2.2.1` which is like 5 years old at this point. Does the checkin script require a certain minimum version of `requests`?

**Comment by pyro2927** [comment]
Ah yea, that would most likely be it.  I'm running the latest versions of the available libraries.  I'll work on defining versions in `requirements.txt`.  For the time being, could you try with the Docker image?  I have an automated build available on the [Docker Hub](https://hub.docker.com/r/pyro2927/southwestcheckin).

**Comment by zxlin** [comment]
I just upgraded my `requests` lib to latest, I will try next time I fly SWA again.

If I encounter this error again the next time, I'll reopen this issue. 

Thanks for entertaining this with me & thanks for this amazing (and moneysaving) script!
