### ISSUE TITLE
name 'time' is not defined

### ISSUE THREAD

**Issue by earlmedina** [pyro2927/SouthwestCheckin#30]
Downloaded this yesterday and encountered this error today when checking in:
`southwest.py", line 39, in safe_request
    time.sleep(CHECKIN_INTERVAL_SECONDS)
NameError: name 'time' is not defined
`
Seems like when the moment came for 'safe_request' to run it couldn't find the time module - looks like the import statement for that is missing?

**Comment by pyro2927** [comment]
Hey @earlmedina, can you update with the latest from today?  This was fixed in https://github.com/pyro2927/SouthwestCheckin/commit/842099332df3cf99f8b20f2135bc208c4d7f848d.
