### ISSUE TITLE
No module named 'openflights'

### ISSUE THREAD

**Issue by futa** [pyro2927/SouthwestCheckin#31]
Thank you so much for this tool! However, for some reason I am receiving this error:
```
Traceback (most recent call last):
  File "./checkin.py", line 26, in <module>
    import openflights
ModuleNotFoundError: No module named 'openflights'
```
Any help would be greatly appreciated!

**Comment by gregrahn** [comment]
Looks like changing
```
import openflights
```
to
```
from southwest import openflights
``` 
solves it.

**Comment by pyro2927** [comment]
@futa and @gregrahn, thank you for reporting! Turns out my test coverage wasn't as good as before, but I fixed the issue and wrote new tests to ensure we don't have a regression!
