### ISSUE TITLE
Can't use the docker image with spaces in name

### ISSUE THREAD

**Issue by kjanoudi** [pyro2927/SouthwestCheckin#34]
When trying to use the docker image, it will not accept spaces in the name as arguments. Quotes or no quotes, it doesn't work. It works fine when running directly using python.

Works:
```
python ./checkin.py ABCDEF FIRST 'LAST NAME' 
```

Doesn't work:

```
docker run -it pyro2927/southwestcheckin:latest ABCDEF FIRST 'LAST NAME'
Usage:
  checkin.py CONFIRMATION_NUMBER FIRST_NAME LAST_NAME [--email=<email_addr> | --mobile=<phone_num>] [-v | --verbose]
  checkin.py (-h | --help)
  checkin.py --version
```

**Comment by rylwin** [comment]
I haven't tried this myself to confirm, but I think the issue might be in the entrypoint.sh line: `python -u ./checkin.py $@`. I think the `$@` needs to be surrounded in quotes to fix this issue: `python -u ./checkin.py "$@"`

**Comment by pyro2927** [comment]
@rylwin thanks, you are correct!  [Quotes added to the entrypoint.sh](73b77d07249008b1a92fd8dfa24505078bc9fd63).
