### ISSUE TITLE
Docker logs

### ISSUE THREAD

**Issue by ShoGinn** [pyro2927/SouthwestCheckin#35]
Because you are using print as the method to show output, in docker you will not get an appropriate log response.

I recommend 
https://github.com/pyro2927/SouthwestCheckin/blob/d7cebbf56f7eefb375ed23c4077c0cf75329c18a/entrypoint.sh#L5

Changing that to 

```
  python -u ./checkin.py $@
```

**Comment by pyro2927** [comment]
Change made, closing issue.
