### ISSUE TITLE
Doesn't seem to work any more?

### ISSUE THREAD

**Issue by bllfr0g** [pyro2927/SouthwestCheckin#37]
Script worked fine for me on Sunday April 7.  Today, April 8, I just get a bunch of blank lines and then an error message.  Tried on multiple machines.

Anyone else getting the same thing?  Did SouthWest change the API?

**Comment by kaseymccurdy** [comment]
It looks like the API_KEY and USER_EXPERIENCE_KEY have changed on southwest's side. I went to the mobile site (https://mobile.southwest.com/) and inspected the traffic, looking at the headers and saw the new values are:

```
API_KEY = 'l7xx0a43088fe6254712b10787646d1b298e'
USER_EXPERIENCE_KEY = '83d21e1e-db65-4b08-88ce-1ebbec5ffeaf'
```

Im not sure how often they change these keys, or what determines them, but when i changed these values in `southwest.py` and re-ran the script, all was happy.

**Comment by pyro2927** [comment]
Closing since #39 has resolved this :)
