### ISSUE TITLE
It appears the mobile API has changed once more

### ISSUE THREAD

**Issue by hakmo** [pyro2927/SouthwestCheckin#43]
Running with a valid confirmation/first/lastname the view-reservation query is returning:

{"code":400120102,"message":"","httpStatusCode":"BAD_REQUEST","requestId":"","infoList":[""]}

**Comment by hakmo** [comment]
Threw in some debug prints for more info, here's the output with unique data redacted:

generate_headers requests.get ok
API_KEY = <REDACTED_API_KEY>
safe_request url=https://mobile.southwest.com/api/mobile-misc/v1/mobile-misc/page/view-reservation/<REDACTED_CFM_NUMER>?first-name=<REDACTED_FIRSTNAME>&last-name=<REDACTED_LASTNAME>
safe_request headers = {'X-API-Key': u'<REDACTED_API_KEY>', 'Host': 'mobile.southwest.com', 'Content-Type': 'application/json', 'Accept': '*/*', 'X-User-Experience-Id': '<REDACTED_USER_EXP_ID>'}
requests.get response status 404
safe_request excepted

**Comment by razierklinge** [comment]
I used the script to check-in to a flight this morning by changing line 71 in southwest.py to:
`return self.load_json_page(self.with_suffix("mobile-air-booking/v1/mobile-air-booking/page/view-reservation/"))`

**Comment by hakmo** [comment]
That's worked for me, thanks!

**Comment by bllfr0g** [comment]
I've submitted a PR to apply this fix

**Comment by pyro2927** [comment]
Closing since #44 has been merged
