### ISSUE TITLE
404 Response up until 24 hours

### ISSUE THREAD

**Issue by hoopsbwc34** [pyro2927/SouthwestCheckin#45]
So the script now crashes when you try to run it more than 24 hours in advance of your checkin.  This is because southwest is returning a "<Response [404 ]>" prior to 24 hours in advance.  This means the script can't get the take off time and sleep right up to check in time.  

The crash happens in auto_checkin and is tied to "for leg in body['bounds']" but the real issue is in southwest/southwest.py, where the value for "r" below is "<Response [404]>" up until 24 hours in advance of checkin. 

```
    def safe_request(self, url, body=None):
        try:
            attempts = 0
            headers = Reservation.generate_headers()
            while True:
                if body is not None:
                    r = requests.post(url, headers=headers, json=body)
                else:
                    r = requests.get(url, headers=headers)
                data = r.json()
```

**Comment by bllfr0g** [comment]
I just tested it and it's working fine for me.

There was a new update to the script a few days ago, due to a SWA API 
change.  Are you running the latest version?

**Comment by hoopsbwc34** [comment]
Ah..that's probably the problem then.  I didn't check for updates

**Comment by hoopsbwc34** [comment]
Yep rookie mistake. Updating fixed the 404 issue.
