### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable -- for leg in body['bounds']:

### ISSUE THREAD

**Issue by justinrhodes** [pyro2927/SouthwestCheckin#47]
Hitting the following error while trying to set up a checkin

Traceback (most recent call last):
  File "./checkin.py", line 103, in <module>
    auto_checkin(reservation_number, first_name, last_name, notifications)
  File "./checkin.py", line 60, in auto_checkin
    for leg in body['bounds']:
TypeError: 'NoneType' object is not subscriptable

**Comment by bllfr0g** [comment]
You have an old version of the tool. There have been API changes at 
Southwest; download the latest version and try again.

**Comment by justinrhodes** [comment]
Yep, that was it. Sorry for the noise.

**Comment by tjs198** [comment]
I'm a dummy to coding, but getting the same error message when running through docker.  how do I update it through docker?  thanks in advance
