### ISSUE TITLE
Docker Run errors

### ISSUE THREAD

**Issue by stgreenb** [pyro2927/SouthwestCheckin#50]
Running 
`$sudo docker run -it pyro2927/southwestcheckin:latest MyRes First Last --email=my@email.com`

Provides the following error
```
Traceback (most recent call last):
  File "./checkin.py", line 103, in <module>
    auto_checkin(reservation_number, first_name, last_name, notifications)
  File "./checkin.py", line 60, in auto_checkin
    for leg in body['bounds']:
TypeError: 'NoneType' object is not subscriptable
```

But takes the commands if I instead run
`$ python ./checkin.py MyRes First Last --email=my@email.com`

**Comment by RayBB** [comment]
@stgreenb I was having the same issue. Try running `docker pull pyro2927/southwestcheckin:latest` to pull the latest version of the docker image.

**Comment by pyro2927** [comment]
Resolved with newer containers
