### ISSUE TITLE
KeyError: 'boardingPasses' when trying to send notifications for companion ticket. 

### ISSUE THREAD

**Issue by treedoan** [pyro2927/SouthwestCheckin#53]
```
Sorry! This reservation is not eligible for check in.
Sorry! This reservation is not eligible for check in.
Sorry! This reservation is not eligible for check in.
Sorry! This reservation is not eligible for check in.
Sorry! We can't check you into this flight. Please see a gate agent.
Sorry! We can't check you into this flight. Please see a gate agent.
Sorry! We can't check you into this flight. Please see a gate agent.
Sorry! We can't check you into this flight. Please see a gate agent.
Sorry! We can't check you into this flight. Please see a gate agent.
Attempting check-in...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./checkin.py", line 43, in schedule_checkin
    data = reservation.checkin()
  File "/home/pi/Desktop/SouthwestCheckin/southwest/southwest.py", line 83, in checkin
    self.send_notification(confirmation)
  File "/home/pi/Desktop/SouthwestCheckin/southwest/southwest.py", line 90, in send_notification
    info_needed = checkindata['_links']['boardingPasses']
KeyError: 'boardingPasses'
```
Not sure if this is related to #23
Attempted to check in for two tickets. One for the original ticket holder and one for the companion. They had different confirmation numbers. The check-in worked just not the notification.

**Comment by janina213** [comment]
May actually be a change in the southwest API, probably worth investigating further.  Unfortunately I don't have a flight soon to test with.  I'll submit a PR that removes the notification options for now

**Comment by treedoan** [comment]
I have a flight coming up on Monday for just me. I'll see if there's the same error and report back.

**Comment by treedoan** [comment]
Same error came up when notifications were enabled.

**Comment by mxxk** [comment]
The error also happened for me, but this conversation got me thinking... @treedoan had a flight to test against, but the only information he could glean is that the error happened again.

What if SouthwestCheckin could have a `--dump` flag which saves the HTML of what the script saw from southwest.com? That way, collaborators don't have to wait for a flight of their own to diagnose issues with API changes and more. Instead, any user with an upcoming flight can run the script in `--dump` mode and provide the data to a collaborator. 😃

There are of course privacy considerations, as the HTML will have the person's full first and last name plus reservation code, but since the script gets those as parameters it can censor it from the saved data output. Food for thought... 🙂

**Comment by bllfr0g** [comment]
It's a great idea!

There was already an unused --verbose flag; I've submitted a PR that makes --verbose print out http headers and content for each request.

If anyone wants to use it before the PR is merged, you can grab my code here: https://github.com/bllfr0g/SouthwestCheckin


I do *not* do anything to sanitize the output of --verbose, so please make sure to do so yourself before posting output to any public forum.

**Comment by pyro2927** [comment]
@bllfr0g added you as a collaborator on the repo so you can just merge stuff in the future :)

**Comment by bllfr0g** [comment]
aw crap now I have actual responsibilities :)

**Comment by bllfr0g** [comment]
BTW I did a checkin today with the new --verbose option.  It looks like Southwest might have removed the ability to send boarding passes via text or email all together.  Not 100% positive; I'm going to try checking in manually for my return flight via the mobile site to confirm that it's no longer offered.

**Comment by bllfr0g** [comment]
I was able to confirm it today; Southwest has removed the ability to send boarding passes via text or email from the mobile API.
