### ISSUE TITLE
Docker image creates other docker containers

### ISSUE THREAD

**Issue by justinrhodes** [pyro2927/SouthwestCheckin#56]
I have this docker image running on my unraid NAS system.

One thing I have noticed that is weird while running this script through the docker image I see other docker containers spawn from this using the standard docker random naming convention (i.e. adoring_wright, compassionate_poitras, etc.)

Is this something that can be explained by how this docker file is set up or something else?

**Comment by pyro2927** [comment]
Hey @justinrhodes, that's probably due to something else.  The Docker container generated by this repo just runs a python script and then exits, nothing more
