### ISSUE TITLE
python3 + pypi update

### ISSUE THREAD

**Issue by ShoGinn** [pyro2927/SouthwestCheckin#63]
Not really an issue, just wanted to say with the obsoleteness of Python2, I have updated the code and made it a legit package that can be uploaded to pypi.

Looking for some feedback and maybe a future merger!

[https://github.com/ShoGinn/SouthwestCheckin](https://github.com/ShoGinn/SouthwestCheckin)

**Comment by ShoGinn** [comment]
also if you are interested.. for other than amd64 docker image...

https://github.com/ShoGinn/swcheckin-docker/

There are:

amd64
arm/v6
arm/v7
arm64

automated builds ;)

**Comment by nathang21** [comment]
I'm interested in arm builds so I can run this on my intel NUC / RBP but I see both the above repos as archived. @ShoGinn

**Comment by ShoGinn** [comment]
@nathang21 I archived them, because it was more of a liability to keep them in the repo without updates. Because of COVID etc I didn't have many test situations.
